fixed release script

diff --git a/onset_maproom/release_container_image b/onset_maproom/release_container_image
--- a/onset_maproom/release_container_image
+++ b/onset_maproom/release_container_image
@@ -9,9 +9,10 @@ fail() {
 }
 
 git_repo=x24-vector
+project_dir=onset_maproom
 imagename=onsetmr
 registry=iridl
-githost=git@github.com:iridl
+githost=git@bitbucket.org:iridl
 labelnamespace=edu.columbia.iri.iridl
 
 cleanup() {
@@ -28,30 +29,29 @@ trap cleanup EXIT
 # build to finish first.
 docker login
 
-builddir=$(mktemp --tmpdir=/tmp --directory build-$git_repo.XXXXXXXXXX) || fail "failed to create build dir"
-git clone \
-  $githost/$git_repo $builddir \
-  || fail "clone failed"
+builddir=$(mktemp --tmpdir=/tmp --directory build-$project_dir.XXXXXXXXXX) || fail "failed to create build dir"
+git clone --recurse-submodules $githost/$git_repo $builddir || fail "clone failed"
+# Can't use --depth 1 because it sometimes causes builds that use git-generate-version-info to fail.
+# Can't use --shallow-submodules because the version of git in CentOS 7 is too old.
 
-cd $builddir
+cd $builddir/$git_dir
 
 commithash=$(git log -1 --pretty=%h) || fail "failed to get git commit hash"
-version=$(cd $imagename && python3 -c 'import __about__; print(__about__.version)')
 
 # Don't overwrite an existing version tag
 existing_tags=$(curl -s https://registry.hub.docker.com/v1/repositories/$registry/$imagename/tags) || \
     fail "Couldn't fetch existing tags."
-echo $existing_tags | grep \"$version\" > /dev/null && \
-    fail "There is already an image tagged $version."
+echo $existing_tags | grep \"$commithash\" > /dev/null && \
+    fail "There is already an image tagged $commithash."
+
 
 docker build \
   -t $registry/$imagename:latest \
-  -t $registry/$imagename:$version \
+  -t $registry/$imagename:$commithash \
   --label $labelnamespace.$imagename.git-commit=$commithash \
-  -f $imagename/Dockerfile \
   . \
   || fail "build failed"
 
-for tag in latest $version; do
+for tag in latest $commithash; do
     docker push $registry/$imagename:$tag || fail "failed to push $tag"
 done
